# 🌀 ReadTheDocs configuration - Eidosian harmony for documentation! 📚✨
# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃              R E A D T H E D O C S   C O N F I G             ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 📋 Version declaration - Protocol adherence with mathematical precision
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
version: 2  # ReadTheDocs configuration format version

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 🏗️ Build environment - Foundation with structural integrity
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
build:
  os: ubuntu-24.04  # LTS version for stability and consistency
  tools:
    python: "3.12"  # Latest stable Python for maximum performance
  jobs:
    pre_build:
      # Self-awareness as foundation - know what we're building
      - echo "📊 Building docs for Repo Forge"
      - pip install pyyaml jinja2  # Explicitly install dependencies before building

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 🐍 Python environment - Precision as style, flow like a river
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
python:
  install:
    - method: pip
      path: .  # Install the package itself first
      extra_requirements:
        - docs  # Install documentation extras from pyproject.toml

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 📘 Sphinx configuration - Structure as control
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
sphinx:
  configuration: docs/conf.py  # Central source of truth
  fail_on_warning: true  # Enforce rigorous documentation quality

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 📦 Output formats - Exhaustive but concise delivery
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
formats:
  - htmlzip  # Compressed HTML for efficient distribution
  - pdf      # Professional PDF for offline reading
  - epub     # E-reader compatibility for universal access
